# SPDX-FileCopyrightText: 2016-2026 Lari Natri <lari.natri@iki.fi>
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Constants shared across the package.
This file is part of the 'ulsbs' package.
"""


ASTRAL_FNAME_PREFIX = "unilaiva-astral"
SELECTION_FNAME_PREFIX = "ul-selection"

LYRICSONLY_FNAMEPART = "_LYRICS-ONLY"
CHARANGO_FNAMEPART = "_CHARANGO"
BASSCLEF_FNAMEPART = "_BASSCLEF"

NODEPLOY_FNAMEPART = "_NODEPLOY"
PAPERA5_FNAMEPART = "_A5"

TEMP_DIRNAME = "temp"
RESULT_DIRNAME = "result"
DEPLOY_DIRNAME = "deploy"
CONTENT_DIRNAME = "content"
INCLUDE_DIRNAME = "include"
TAG_DEFINITION_FILENAME = "tags.can" # under INCLUDE_DIRNAME

RESULT_SEPARATOR = "\t"
RESULTLIST_BASENAME = "ulsbs-results"

RESULT_TYPE_INFO           = "INFO          "
RESULT_TYPE_MAIN_PDF       = "MAINPDF       "
RESULT_TYPE_PRINTOUT_PDF   = "PRINTOUTPDF   "
RESULT_TYPE_IMAGE          = "IMAGE         "
RESULT_TYPE_MIDIDIR        = "MIDIDIR       "
RESULT_TYPE_AUDIODIR       = "AUDIODIR      "
RESULT_TYPE_COMMONICON     = "COMMONICON    "
RESULT_TYPE_COMMONMETADATA = "COMMONMETADATA"
RESULT_TYPE_COMMONOTHER    = "COMMONOTHER   "

RESULT_PRINTOUT_SUBDIRNAME = "printouts"
RESULT_IMAGE_SUBDIRNAME = "images"
RESULT_MIDI_SUBDIRNAME = "midi"
RESULT_AUDIO_SUBDIRNAME = "audio"
RESULT_COMMON_SUBDIRNAME = "other"

DEPLOY_IMAGE_SUBDIRNAME = "images"
DEPLOY_PRINTOUT_SUBDIRNAME = "printouts"
DEPLOY_AUDIO_SUBDIRNAME = "audio"
DEPLOY_MIDI_SUBDIRNAME = "midi"
DEPLOY_COMMONICON_SUBDIRNAME = f"{RESULT_IMAGE_SUBDIRNAME}/icons"
DEPLOY_COMMONMETADATA_SUBDIRNAME = "metadata"
DEPLOY_COMMONOTHER_SUBDIRNAME = "other"

SONG_IDX_SCRIPT_REL = "ulsbs/src/ulsbs/assets/tex/ext_packages/songs/songidx.lua"
SORT_LOCALE = "fi_FI.utf8"

COVERIMAGE_HEIGHT = "1024"
COVERIMAGE_AUTOWIDE_WIDTH = "976"
IMG_AUTOWIDENOTAGS_FNAME_POSTFIX = "_AUTOWIDENOTAGS"
