# Client config file for PipeWire version "1.6.2" #
#
# This is stripped down, as we are not using Pipewire. This is only included
# to make fluidsynth's logging happy. :)
#
# This file

context.modules = [
    # The native communication protocol.
    { name = libpipewire-module-protocol-native }

    # Allows creating nodes that run in the context of the
    # client. Is used by all clients that want to provide
    # data to PipeWire.
    { name = libpipewire-module-client-node
        condition = [ { module.client-node = !false } ]
    }

    # Allows creating devices that run in the context of the
    # client. Is used by the session manager.
    { name = libpipewire-module-client-device
        condition = [ { module.client-device = !false } ]
    }

    # Makes a factory for wrapping nodes in an adapter with a
    # converter and resampler.
    { name = libpipewire-module-adapter
        condition = [ { module.adapter = !false } ]
    }

    # Allows applications to create metadata objects. It creates
    # a factory for Metadata objects.
    { name = libpipewire-module-metadata
        condition = [ { module.metadata = !false } ]
    }

    # Provides factories to make session manager objects.
    { name = libpipewire-module-session-manager
        condition = [ { module.session-manager = !false } ]
    }
]
